### ISSUE TITLE
Unable to compile with the latest commit

### ISSUE THREAD

**Issue by designgears** [retronx-team/sys-clk#12]
https://pastebin.com/zuDMK7kA

**Comment by p-sam** [comment]
Yup that's expected, you currently need to use our fork of libnx until pr is merged upstream
https://github.com/p-sam/libnx/tree/pcv-8

**Comment by designgears** [comment]
Ah, ok, I guess I didn't look hard enough at your libnx fork. Thanks for pointing that out.

**Comment by p-sam** [comment]
btw, the libnx PR has been merged so develop/master have been updated with the latest changes, and is expected to compile and run on current libnx master
