### ISSUE TITLE
Feature Request: Idle mode

### ISSUE THREAD

**Issue by fennectech** [retronx-team/sys-clk#17]
I would like to see an 'idle mode' Where you can choose to set the clocks after no buttons on the controler are pushed for a moment (and a flag to disable this on a game by game basis for apps like youtube)  
Basicly   We could push clocks to minimums if the console hasent been touched for an ammount of time.   This would reduce wear on the console for time its left idle but powered on.

**Comment by m4xw** [comment]
> and a flag to disable this on a game by game basis for apps like youtube

.. then don't add a overclock for the title?

Since you didn't come up with a proper use-case and the example you stated is literally no Issue, we unanimously decline this.
