### ISSUE TITLE
error code: 2021-0004 then starting console

### ISSUE THREAD

**Issue by Skalke** [retronx-team/sys-clk#2]
![image](https://user-images.githubusercontent.com/10077834/52814631-a65b7d80-30ad-11e9-9b74-c1a11a63bf22.png)
I'm also using ldn_mitm.kip (but without its problem don't sovled).

**Comment by Skalke** [comment]
log:
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000

**Comment by m4xw** [comment]
Ini contents?

**Comment by Skalke** [comment]
; The Legend of Zelda: BOTW
; Overclock CPU when docked
; Overclock MEM to docked clocks when handheld
[01007EF00011E000]
docked_cpu=1224
handheld_mem=1600
; Example #2: Picross
; Underclock to save battery
[0100BA0003EEA000]
handheld_cpu=816
handheld_gpu=153.6
handheld_mem=800
#Pokemon Lets go Eevee
#Helps reduce UI slowdowns as well as varidian forest.
[0100187003A36000]
handheld_gpu=460
#New Super Mario Bros. U Deluxe
#Underclock to save battery
[0100EA80032EA000]
handheld_cpu=816
handheld_mem=800
#Qlaunch
#If you want to save battery in handheld mode while not in a game and not compromise on useablilty.
[0100000000001000]
handheld_cpu=816
handheld_gpu=230
handheld_mem=800
#Super Smash Bros
#Fast loading times, great in game battle speeds and nice battery savings
[01006A800016E000]
handheld_cpu=1220
handheld_gpu=230
handheld_mem=1600
#Monster Hunter Generations Ultimate
# Overclock then docked

**Comment by m4xw** [comment]
Try removing the qlaunch entry

**Comment by Skalke** [comment]
;The Legend of Zelda: BOTW
;Overclock CPU when docked
;Overclock MEM to docked clocks when handheld
[01007EF00011E000]
docked_cpu=1224
handheld_mem=1600
;Pokemon Lets go Eevee
;Helps reduce UI slowdowns as well as varidian forest.
[0100187003A36000]
handheld_gpu=460
;New Super Mario Bros. U Deluxe
;Underclock to save battery
[0100EA80032EA000]
handheld_cpu=816
handheld_mem=800
;Qlaunch
;If you want to save battery in handheld mode while not in a game and not compromise on useablilty.
;[0100000000001000]
;handheld_cpu=816
;handheld_gpu=230
;handheld_mem=800
;Super Smash Bros
;Fast loading times, great in game battle speeds and nice battery savings
[01006A800016E000]
handheld_cpu=1220
handheld_gpu=230
handheld_mem=1600
;Monster Hunter Generations Ultimate
;Overclock then docked

**Comment by Skalke** [comment]
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000

it's still feel qlaunch config then commented lol

**Comment by m4xw** [comment]
Works for me.

**Comment by m4xw** [comment]
Double check your installation.
I used your ini.

**Comment by Skalke** [comment]
i'm trying....qlauch deleted is not working lol....maybe it themes?)

**Comment by Skalke** [comment]
hahaha log 
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
* Setting cpu clock to 816000000
* Setting gpu clock to 230400000
* Setting mem clock to 800000000
* cpu clock is now 816000000
* gpu clock is now 230400000
* mem clock is now 800000000
=== sys-clk boot ===
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini
=== sys-clk boot ===
Ready
* ApplicationTid changed to: 0100000000001000
* Charger type changed to: None
* cpu clock is now 1020000000
* gpu clock is now 307200000
* mem clock is now 1331200000
[cfg] reading /config/sys-clk/config.ini

**Comment by Skalke** [comment]
yeah maybe problem in my side....

**Comment by p-sam** [comment]
Are you by any chance using BrowserNX ?

**Comment by Skalke** [comment]
yeah it's could be browser-nx....just checked...****...titleids

**Comment by p-sam** [comment]
I think you might still have an old version of sys-tweak, check for the `01FF415446660000` folder in `/atmosphere/titles`, delete if present, because you would have 2 times the same sysmodule

**Comment by crc-32** [comment]
The info to remove the old sysmodule was included in the release page of browsenx :stuck_out_tongue:

**Comment by Skalke** [comment]
i find it! wait

**Comment by p-sam** [comment]
I will leave the issue closed then, as it's unrelated to sys-clk. I guess you're lucky that the title-id reminded me of something...

**Comment by Skalke** [comment]
titleid - 01FF415446660000 by @crc-32 i think)
or wait...my ***king files...

**Comment by Skalke** [comment]
it's conflict with some titleids maybe...later i tell what was my problem
