### ISSUE TITLE
When a game is running, I cannot open the HBmenu by album.

### ISSUE THREAD

**Issue by Conan179** [retronx-team/sys-clk#20]
Hello@all.
I have a problem.
When a game is running, I cannot open the HBmenu by album, everytime i become a:
"Panic occurred while running Atmossphere.
Title ID: 010041544D530000
Error Desc: std::abort<> <0xFFE>

Press POWER to continue."

without or disabled sys-clk, this massange dosnt come and my switch dosnt make reboot.
OS 10.0.02|AMS 0.12.0|S no emummc.

**Comment by p-sam** [comment]
Hello, can you tell me more about what you have installed right now? Like a screenshot of your /atmosphere/contents folder

**Comment by Conan179** [comment]
No Problem.
![atmos_content_08052020a](https://user-images.githubusercontent.com/1906242/81380792-bd034f80-910b-11ea-81f4-bb2626a4f211.JPG)

**Comment by p-sam** [comment]
Can you try with just clean Atmosphère and sys-clk, it looks like you have many different sysmodules installed and mods, also what's your config.ini like ?

**Comment by Conan179** [comment]
Yes, it test it.
All clean no problems.
sys-ftpd-light restored, no problems.
Teslamenu restord no problems.
https://github.com/olliz0r/sys-botbase restored, problem again.

ok the combi from sys-clk and sys-botbase make problem.

**Comment by m4xw** [comment]
It's more about the number of modules and their mem consumption.
