### ISSUE TITLE
Instant crash when using Tesla v1.0.6 & sys-clk-Overlay

### ISSUE THREAD

**Issue by TheFriendlyBroski** [retronx-team/sys-clk#22]
I'm currently running my Switch on system version 9.2.0|AMS 0.12.|S and I'm using both Tesla v1.0.6 & sys-clk-Overlay 1.1.1

My issue is that whenever I'm attempting to use the overclocking overlay in game or elsewhere on my Switch, it instantly crashes.

Not sure what's causing the issue.

**Comment by Conan179** [comment]
The problem is sys-clk-Overlay not sys-clk ;)
https://github.com/Sun-Research-University/sys-clk-Overlay/issues/28

**Comment by TheFriendlyBroski** [comment]
> The problem is sys-clk-Overlay not sys-clk ;)
> [Sun-Research-University/sys-clk-Overlay#28](https://github.com/Sun-Research-University/sys-clk-Overlay/issues/28)

Thanks for the heads up! I'm not familiar with using GitHub, thanks for pointing me to the right direction.
