### ISSUE TITLE
Cannot show Korean characters. (sys clk manager)

### ISSUE THREAD

**Issue by uaevuon** [retronx-team/sys-clk#23]
![2020061801192200-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/84923340-0c24a300-b102-11ea-997b-aec6422e84a7.jpg)
It shows english and japanese properly but cannot show korean characters.

**Comment by p-sam** [comment]
That's unfortunate, we're probably not loading the required fonts for Korean (and also Chinese), i'll open a relevant issue in borealis so we can track that out

**Comment by p-sam** [comment]
Can you confirm if the Korean characters show on this version of the manager app? (No app specific changes were made, but borealis was rebased at commit fcc06642, which should fix it)

[sys-clk-manager.nro.zip](https://github.com/retronx-team/sys-clk/files/4808707/sys-clk-manager.nro.zip)

**Comment by uaevuon** [comment]
![2020062112532500-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/85216338-44f0a080-b3be-11ea-8c59-123ed61bc365.jpg)
Fixed.

**Comment by p-sam** [comment]
Fixed by fcc06642
