### ISSUE TITLE
Is sys-clk manager missing the skin's temperature?

### ISSUE THREAD

**Issue by Heartbeat-Heartbreak** [retronx-team/sys-clk#24]
![CAP](https://user-images.githubusercontent.com/52705310/85022850-72630180-b1a6-11ea-84db-237d2efba439.jpg)

**Comment by p-sam** [comment]
It's not currently displayed in the manager

**Comment by masterchan-777** [comment]
A suggested solution to this 
![sys-clk](https://user-images.githubusercontent.com/26387181/85213094-be9e7500-b351-11ea-8963-5d59d2d40c99.jpg)

**Comment by p-sam** [comment]
Thanks for the suggestion, I answered in the associated PR
