### ISSUE TITLE
Manager app doesn't build under msys2

### ISSUE THREAD

**Issue by masterchan-777** [retronx-team/sys-clk#26]
Trying to build the manager app using build.sh gives the following build error :

`*** manager ***
/c/switchdev/sys-clk/manager /c/switchdev/sys-clk
Merging ROMFS...
about_tab.cpp
advanced_settings_tab.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/about_tab.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/about_tab.cpp -o about_tab.o
app_profile_frame.cpp
app_profiles_tab.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/advanced_settings_tab.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/advanced_settings_tab.cpp -o advanced_settings_tab.o
cheat_sheet_tab.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/app_profile_frame.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/app_profile_frame.cpp -o app_profile_frame.o
logo.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/app_profiles_tab.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/app_profiles_tab.cpp -o app_profiles_tab.o
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/cheat_sheet_tab.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/cheat_sheet_tab.cpp -o cheat_sheet_tab.o
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/logo.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/logo.cpp -o logo.o
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
main.cpp
main_frame.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/main.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/main.cpp -o main.o
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/main_frame.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/main_frame.cpp -o main_frame.o
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: error: missing terminating " character
<command-line>: note: in definition of macro 'APP_RESOURCES'
C:/switchdev/sys-clk/manager/src/logo.h:34:24: note: in expansion of macro 'APP_ASSET'
   34 | #define LOGO_FONT_PATH APP_ASSET("fira/FiraSans-Medium-rnx.ttf")
      |                        ^~~~~~~~~
C:/switchdev/sys-clk/manager/src/main.cpp:47:53: note: in expansion of macro 'LOGO_FONT_PATH'
   47 |     if (brls::Application::loadFont(LOGO_FONT_NAME, LOGO_FONT_PATH) < 0)
      |                                                     ^~~~~~~~~~~~~~
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:188: build.nx] Error 2
`

Trying to build the manager app using standard make command gives the same error too
`Merging ROMFS...
about_tab.cpp
advanced_settings_tab.cpp
app_profile_frame.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/about_tab.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/about_tab.cpp -o about_tab.o
app_profiles_tab.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/advanced_settings_tab.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/advanced_settings_tab.cpp -o advanced_settings_tab.o
cheat_sheet_tab.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/app_profile_frame.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/app_profile_frame.cpp -o app_profile_frame.o
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/app_profiles_tab.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/app_profiles_tab.cpp -o app_profiles_tab.o
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/cheat_sheet_tab.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/cheat_sheet_tab.cpp -o cheat_sheet_tab.o
logo.cpp
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/logo.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/logo.cpp -o logo.o
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
main.cpp
main_frame.cpp
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/main.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/main.cpp -o main.o
aarch64-none-elf-g++ -MMD -MP -MF /c/switchdev/sys-clk/manager/build.nx/main_frame.d -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE  -I/c/switchdev/sys-clk/manager/../common/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/glad -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/nanovg -I/c/switchdev/sys-clk/manager/lib/borealis/library/include/borealis/extern/libretro-common -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/switchdev/sys-clk/manager/build.nx -D__SWITCH__ -DAPP_TITLE="\"sys-clk manager\"" -DBOREALIS_RESOURCES="\"romfs:/borealis/\"" -DAPP_RESOURCES="\"romfs:/\"" -std=c++1z -c /c/switchdev/sys-clk/manager/src/main_frame.cpp -o main_frame.o
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: warning: missing terminating " character
<command-line>: error: missing terminating " character
<command-line>: note: in definition of macro 'APP_RESOURCES'
C:/switchdev/sys-clk/manager/src/logo.h:34:24: note: in expansion of macro 'APP_ASSET'
   34 | #define LOGO_FONT_PATH APP_ASSET("fira/FiraSans-Medium-rnx.ttf")
      |                        ^~~~~~~~~
C:/switchdev/sys-clk/manager/src/main.cpp:47:53: note: in expansion of macro 'LOGO_FONT_PATH'
   47 |     if (brls::Application::loadFont(LOGO_FONT_NAME, LOGO_FONT_PATH) < 0)
      |                                                     ^~~~~~~~~~~~~~
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:188: build.nx] Error 2
`

**Comment by p-sam** [comment]
I'm aware, this is due to wrong path conversion if you try to build under msys2 on windows. Use Linux directly or WSL to build instead, or wait until the Makefile is changed to mitigate this.
