### ISSUE TITLE
sys-clk does not seem to be running, please check that it is correctly installed and enabled

### ISSUE THREAD

**Issue by paineone** [retronx-team/sys-clk#30]
i have installed on CFW 10.0.4 with Atmosphere 0.13.
On Tesla Overview sys-clk is ON

when i try to start sys-clk manager over hbmenu i got error:
sys-clk does not seem to be running, please check that it is correctly installed and enabled

**Comment by paineone** [comment]
On 
sys-clk Editor by SunTheCourier
(https://github.com/SunTheCourier/sys-clk-Editor)

it works but i wanna GUI interface....

so why dont work sys-clk manager?

**Comment by p-sam** [comment]
Make sure you're using the latest release (a reboot is needed after install/update), and that you're using the overlay and manager included in this release

**Comment by paineone** [comment]
i have v1.0.0, this is the lastest version or not?
i have deinstalled it, reboot, new install, than in hbmenu in manager = sys-clk does not seem to be running, please check that it is correctly installed and enabled

**Comment by paineone** [comment]
i got it. 
dont run in applet mode! 
applet mode = sys-clk does not seem to be running, please check that it is correctly installed and enabled

**Comment by p-sam** [comment]
Are you sure of what you're saying? You're running the exact same homebrew. 

I'm going to close this right now as either something weird is going on because either you're using SX OS, or you terminated the sysmodule process one way or another. FWIW, running it as applet has been tested running, and while it can OOM, it does not exhibit the behavior you're describing.

**Comment by Stevoisiak** [comment]
For anyone else with this issue, try installing Tesla from the HB App Store.

**Comment by Originalimoc** [comment]
More like HOS version 17.0.0 is not supported by 1.x.x

**Comment by p1gyy** [comment]
Found the issue. Seems as though the dev abandoned the project and HOS V17.0.0 isn't supported by sys-clk. I found a fork that works wonderfully, and has extra features!
https://github.com/jope82/sys-clk-uncapped-gpu-and-other-extras

**Comment by p-sam** [comment]
@p1gyy That's not true, we're still maintaining the project though the latest release is marked as 2.0.0-rc
