### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by zal16** [retronx-team/sys-clk#32]
I'm running on Ubuntu 20.04.1 LTS and this error appears when I try to compile:

DIST_DIR: /home/zal/Desktop/sysclk/sys-clk/dist
CORES: 8
*** sysmodule ***
/home/zal/Desktop/sysclk/sys-clk/sysmodule /home/zal/Desktop/sysclk/sys-clk
fatal: bad revision 'HEAD'
minIni.c
make[2]: aarch64-none-elf-gcc: Command not found
make[2]: *** [/home/zal/Desktop/sysclk/sys-clk//devkitA64/base_rules:19: minIni.o] Error 127
make[1]: *** [Makefile:99: lib/libminIni.a] Error 2
make: *** [Makefile:113: libs] Error 2

**Comment by p-sam** [comment]
I'd suggest checking the readme for setting up a correct development environment, but this is not a support forum, and you're the person from the other issue
