### ISSUE TITLE
[Feature request] Fan Controls

### ISSUE THREAD

**Issue by PABLEXWorld** [retronx-team/sys-clk#36]
I was wondering how feasible is it to customize the way the Switch handles the fan. Maybe we could get something out of having it ramp up its fan earlier (much like fan curves on a PC) or forcing it at 100% while playing overclocked titles. I don't care about potentially having a lot of noise, I'd just like to know whether something like this is possible (is it something the OS controls?), what the implications can be, and if there could be anything to gain from doing it. Oh, and if it's something you'd consider worth putting the effort into.

**Comment by p-sam** [comment]
Custom fan speeds are possible directly using atmosphere system settings override, there's a config pinned in channel #oc-discussion in our discord
https://discord.gg/ZnFPaMFHQG

**Comment by PABLEXWorld** [comment]
Oh, good. Thanks and sorry for bothering.
