### ISSUE TITLE
What Qualifies As “Official Charger”?

### ISSUE THREAD

**Issue by Bowser-Alt** [retronx-team/sys-clk#37]
I recently bought a power bank because I thought it would let me use the switch at its max power but it’s in usb instead of official charger. Just wanted to know if I could buy a cord that would make the switch think it’s an official charger and let me carry it portable. Also if there is no portable cord for that can someone coach me on how to edit the code to make it do so? Thanks

**Comment by Masamune3210** [comment]
The charger itself and the switch communicate over USB-PD to determine the capabilities. other than either ignoring pd on the switch side or a cable that mitms the data somehow there is no changing it. 

both are unsafe mind you, those limits are there for a reason

**Comment by p-sam** [comment]
"Official charger" is what the console identifies to be enough for the dock (39W)

**Comment by Bowser-Alt** [comment]
So if I get a 39W charging cable will it show as official charger?

**Comment by Bowser-Alt** [comment]
> "Official charger" is what the console identifies to be enough for the dock (39W)

So if I get a 39W charging cable will it show as official charger?

**Comment by p-sam** [comment]
No the cable doesn't qualify on its own, I suggest that you join in our discord, I didn't buy any power bank for the switch, but there might be some of our users that did and can advise you

**Comment by Bowser-Alt** [comment]
> 
> 
> No the cable doesn't qualify on its own, I suggest that you join in our discord, I didn't buy any power bank for the switch, but there might be some of our users that did and can advise you

Damn, What's the link to the discord server?

**Comment by p-sam** [comment]
https://discord.gg/AARQb9TdaG
