### ISSUE TITLE
Sys_clk does not work on latest atmosphere update 0.19.4

### ISSUE THREAD

**Issue by sardelisp** [retronx-team/sys-clk#39]
The issue is that it cannot run ..
Switch is bootable. Does not cause any other issue, only that cannot run

**Comment by p-sam** [comment]
Hi, first thing you should do is upload the log file of sys-clk, it's located on your sdcard at /config/sys-clk/log.txt

**Comment by sardelisp** [comment]
🤷🏻‍♂️don't know what happened !!?? After few reboots and uninstallations it works.
😐 Sorry
