### ISSUE TITLE
Add an "all" header

### ISSUE THREAD

**Issue by Elionna** [retronx-team/sys-clk#4]
Instead of having to manually put in the same configs under different titleids, it would be nice to have an option for an "all" setting that applies the config to every game. 

For example:

[ALL]
handheld_charging_official_gpu=768
handheld_charging_official_mem=1600

**Comment by p-sam** [comment]
While a manual override may be added when the GUI comes which would allow to do some testing without the need to edit your config, adding a "catch-all" config goes against the idea of sys-clk trying to apply the best profile for each game.
