### ISSUE TITLE
Compatiility with FW 13 and Atmosphere 1.1.1

### ISSUE THREAD

**Issue by magarto** [retronx-team/sys-clk#44]
Hi,

Last sys-clk release is not compatible with FW 13.0 and atmosphere 1.1.1
Would it be compiled again?

Thanks in advance!

**Comment by pouyaman** [comment]
Working fine on my end.  
Same setup as you, FW 13 and Atmosphere 1.1.1  
Had sys-clk: 1.0.0 and just updated to 1.0.1 with no issues.

**Comment by magarto** [comment]
Thanks, maybe any file in my microsd was wrong. I reinstalled it and worked fine. Thanks!
