### ISSUE TITLE
Latest beta / commit crashes system on boot

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [retronx-team/sys-clk#5]
2168-0002, no crash report was generated, but fatal shows, so I will try some more to get a crash report.

All debug values are blank on fatal too.

**Comment by p-sam** [comment]
Could you try and give more details, as what version you used, if you compiled yourself, and what version of atmosphère you're using and additionnal titles running please

**Comment by ThatNerdyPikachu** [comment]
Latest master AMS, 7.0.1, latest master sys-clk, all compiled on my machine with no errors. I also tried the release build. INI contains Smash config from the DB repo, and no other sysmodules except this and default AMS ones.

**Comment by p-sam** [comment]
Also:
* Do you have the log flag enabled? If yes, is there a log file you can send?
* Did you use latest libnx pacman package, or compiled from master

**Comment by m4xw** [comment]
I smell layer8

**Comment by p-sam** [comment]
ping @ThatNerdyPikachu

**Comment by ThatNerdyPikachu** [comment]
@p-sam latest libnx master

Layer8?

**Comment by p-sam** [comment]
Yea that's the reason, changes regarding the hosversion/kernelAboveXXX refactor on libnx are needed. Since we have to choose either breaking compiling against latest libnx stable or master, changes will be integrated when the next version of libnx is tagged and released.

**Comment by p-sam** [comment]
the api compat changes were pushed to github
