### ISSUE TITLE
Why does the overclocking plug-in still show that I am in USB charging mode when my ns Lite is switched to docked mode.

### ISSUE THREAD

**Issue by zf021600** [retronx-team/sys-clk#51]
Why does the overclocking plug-in still show that I am in USB charging mode when my ns Lite is switched to docked mode.

**Comment by zf021600** [comment]
为什么当我的ns lite切换到docked模式的时候，超频插件依然显示我为USB充电模式。

**Comment by zf021600** [comment]
Why does the overclocking plug-in still show that I am in USB charging mode when my ns Lite is switched to docked mode.

**Comment by p-sam** [comment]
Hi, AFAIK the switch lite can't be docked
