### ISSUE TITLE
sys-clk does not seem to be running, please check that it is correctly installed and enabled

### ISSUE THREAD

**Issue by MelvinSmiley** [retronx-team/sys-clk#56]
I'm on atmosphere 1.3.2 and sys-clk 10.2 just won't work for me, no matter what I do. Always get the error message above. 

Does not work from Tesla menu, error messsage "Fatal error. sys-clk is not running. Please make sure it is correctly installed and enabled." 
From hbmenu I get "sys-clk does not seem to be running, please check that it is correctly installed and enabled." I have all the required files on SD card, deleted and copied them countless times and spent many hours trying to get this to work, it just won't. 
It's the only CFW software on my system acting in such a strange way, everything else works fine.

Edit: logs seem to indicate that the module itself is working fine, it's just the overlay that is broken for some reason.

**Comment by Christchex** [comment]
Same here. 1.3.2 and 1.0.2

**Comment by p-sam** [comment]
If you didn't already get user support in Discord (judging by the issue creation time), feel free to join, I'll be closing this issue in the meantime
