### ISSUE TITLE
"sys-clk does not seem to be running, please check that it is correctly installed and enabled​"

### ISSUE THREAD

**Issue by gittyno1** [retronx-team/sys-clk#60]
I get this Error ether when i run app from HBmenu, or as an overlay from Tesla menu. Any solution or reason why this happens?
I dragged and dropped files to root of SD as usual.

I'm runing: 15.0.1|AMS 1.4.0|E

**Comment by p-sam** [comment]
Might want to check and properly copy files again, anyway you should probably seek support on Discord, it's probably not a bug considered the user reports from the previous weeks
