### ISSUE TITLE
16.0.0 support... 

### ISSUE THREAD

**Issue by josete2k** [retronx-team/sys-clk#61]
Thanks in advance...

**Comment by Pauli343** [comment]
@alula has already added an update. Its stuck in Pull Request.
I have relinked it for you, just use the attached Zip.
[sys-clk-overlay.zip](https://github.com/retronx-team/sys-clk/files/10831754/sys-clk-overlay.zip)

**Comment by Minecraftplayer20** [comment]
> @alula has already added an update. Its stuck in Pull Request. I have relinked it for you, just use the attached Zip. (unzip it of course) [sys-clk-overlay.zip](https://github.com/retronx-team/sys-clk/files/10831754/sys-clk-overlay.zip) EDIT: you are probably in search of a Sysmodules fix too [ovlSysmodules.zip](https://github.com/retronx-team/sys-clk/files/10831776/ovlSysmodules.zip)

Where do I put the files?

**Comment by Pauli343** [comment]
Hi, 

On your SD Card under /switch/.overlays/

Make sure to unzip them first.

Best Regards,

Paul

 

Von: Minecraftplayer20 ***@***.***> 
Gesendet: Montag, 6. März 2023 23:12
An: retronx-team/sys-clk ***@***.***>
Cc: Paul343 ***@***.***>; Manual ***@***.***>
Betreff: Re: [retronx-team/sys-clk] 16.0.0 support... (Issue #61)

 

@alula <https://github.com/alula>  has already added an update. Its stuck in Pull Request. I have relinked it for you, just use the attached Zip. (unzip it of course) sys-clk-overlay.zip <https://github.com/retronx-team/sys-clk/files/10831754/sys-clk-overlay.zip>  EDIT: you are probably in search of a Sysmodules fix too ovlSysmodules.zip <https://github.com/retronx-team/sys-clk/files/10831776/ovlSysmodules.zip> 

Where do I put the files?

**Comment by Nazosan** [comment]
I updated with the above provide files and I still get no overlay when I press the L+down+r-stick shortcut.  Has the shortcut been changed or something?

**Comment by Pauli343** [comment]
Be sure to update the Tesla Menu itself too.
You can find the updated Files here:
https://github.com/ELY3M/Tesla-Menu/releases/

**Comment by Nazosan** [comment]
Oh, sorry, you can disregard that.  I actually did have that, but I had had to clear out my /atmosphere/contents folder of all extraneous content to try to resolve a crash on startup and accidentally forgot to restore nx-ovlloader (as a side note, a note and link to it should possibly be mentioned in these projects given that they...  kind of require it...)

**Comment by tylearymf** [comment]
> @alula has already added an update. Its stuck in Pull Request. I have relinked it for you, just use the attached Zip. (unzip it of course) [sys-clk-overlay.zip](https://github.com/retronx-team/sys-clk/files/10831754/sys-clk-overlay.zip) EDIT: you are probably in search of a Sysmodules fix too [ovlSysmodules.zip](https://github.com/retronx-team/sys-clk/files/10831776/ovlSysmodules.zip)

👍

**Comment by m4xw** [comment]
The team is still stuck in purgatory

**Comment by Nazosan** [comment]
If it's not being worked on anymore should it be forked?

BTW I don't know if this is where to ask or not, but with the updates provided here I'm getting full system crashes whenever I actually use the overlay to configure anything.  It sets the setting and then crashes moments later (so at least after rebooting the setting is in place and I'm free of crashes -- so long as I don't need to change it again...)

**Comment by treyturner** [comment]
I just spent a few hours trying to figure out why I was still crashing after updating to the 1.0.2 release from March 23 before realizing that's March _2022_. So if anyone stumbles on this thread, yes, you still need the version attached above! 😅 Most threads I've found discussing this just say 'grab the update'.

**Comment by Nazosan** [comment]
Yes, Atmosphere made some important changes that make this necessary.  Though I'm still getting crashing in the overlay when making changes even with updated versions of both modules.  If anyone else experiences the problem I'm having, it seems that the best chance of avoiding a crash is to make only one change at a time and each time press home to go back to the main menu and force close out of the overlay all at once after each change.  Then it only is likely to crash once per new game.

It's kind of sad seeing updates currently stuck at a time like this given how many games seem to be very poorly optimized for the Switch (to the point I actually found one or two to be basically unplayable without raising the clocks in fact.  And I'm not even that picky when it comes to console ports.)

**Comment by Pauli343** [comment]
@Nazosan have the same issues, was looking into it last week but dont have time for any development work r8n. Maybe after end of May when my Master Thesis is done.
Till then there are already many [forks ](https://github.com/retronx-team/sys-clk/forks?include=active&page=1&period=2y&sort_by=last_updated). If anyone has time on hand and could try some and report if one has better stability would help out a lot.

**Comment by Nazosan** [comment]
Thanks for letting me know what's going on at least.  Do I correctly understand that undocking it to do the menu might solve the crash at least?  That is really not all that bad as a temporary solution if so.
