### ISSUE TITLE
Wrong Version Number

### ISSUE THREAD

**Issue by xsynatic** [retronx-team/sys-clk#62]
Module shows up as 1.0.1 (-5-gdcg0d5) in the overlay and in the HBMenu preview. 

Inside the Sys-clk manager it shows 1.0.2

![grafik](https://user-images.githubusercontent.com/73779312/221213124-9ff92ad4-1c70-4e62-a501-742f9b1e020d.png)

![grafik](https://user-images.githubusercontent.com/73779312/221213234-597f2152-4bf4-4374-acc8-ea09b4f1f523.png)

Inside the manager:

![grafik](https://user-images.githubusercontent.com/73779312/221213332-931a349c-24f2-4851-98c8-3140a3e57e4a.png)

**Comment by p-sam** [comment]
Should be fixed in 1.0.3
