### ISSUE TITLE
error 2168-0002 when opening from docked mod

### ISSUE THREAD

**Issue by GreyGun21** [retronx-team/sys-clk#66]
i have no issues with it in handheld mode , but as soon as i open sys clk from tesla menu in docked mod the switch freeze for 1-2 seconds and then i get the error, using 1.16.0.2 with latest atmosphere

**Comment by inspectah88** [comment]
it needs to be recompiled with latest libtesla and libnx.
the bug was fixed here:
https://github.com/switchbrew/libnx/pull/606

**Comment by admiralspeedy** [comment]
> it needs to be recompiled with latest libtesla and libnx. the bug was fixed here: [switchbrew/libnx#606](https://github.com/switchbrew/libnx/pull/606)

It already was 2 weeks ago, unless they accidentally used the last actual libnx release and not master, which is mixing the fix.

**Comment by kamikazilucas** [comment]
its crashing for me too but only in docked mode in handheld its fine

**Comment by admiralspeedy** [comment]
> its crashing for me too but only in docked mode in handheld its fine

And you're certain you're using 1.0.3 from two weeks ago?

**Comment by GreyGun21** [comment]
> > its crashing for me too but only in docked mode in handheld its fine
> 
> And you're certain you're using 1.0.3 from two weeks ago?

i am using the 1.0.3

**Comment by admiralspeedy** [comment]
Then you are using an outdated Tesla Menu because it works fine if you use one with the race condition fix. I just tested it on my console and sys-clk works totally fine while docked.

Go download the update for Tesla that came out today.

**Comment by GreyGun21** [comment]
yes now it works, thank you
