### ISSUE TITLE
[Newbie] i open sys-clk-manager and it says "The software was closed because an error occured." (17.0.0)

### ISSUE THREAD

**Issue by Octogonee** [retronx-team/sys-clk#72]
I dont really know what to give you so if you need anything ill tell you. Thank you

**Comment by p-sam** [comment]
Update atmosphère and grab the latest prerelease

**Comment by Octogonee** [comment]
@p-sam I did that. Atmosphere is latest and i put the prerelease on the root of the SD card.

**Comment by Inzocknito** [comment]
sys-clk is unable to start at FW 17.0.0 + Atmosphere 1.6.1 / 1.6.2

**Comment by Octogonee** [comment]
ah

**Comment by Octogonee** [comment]
that or i could be doing something wrong.

**Comment by Inzocknito** [comment]
sys-clk seems to be not compatible with the new firmware....

**Comment by Octogonee** [comment]
the prerelease is

**Comment by Octogonee** [comment]
badabump. still not workin

**Comment by TheDBPI** [comment]
I'm facing the same issue. The nro file always crashes but it works from the tesla menu. I have F 17.0.0  6.0.7 hekate and AMS 1.6.2
Using the 2.0.0-rc.
I tried with the previous version of sys clk but it didn't work.

**Comment by PolyCatGamedev** [comment]
Hi there. I thought I had this problem, but today I realized that my game crash came from having saltynx and nxfps installed (homebrew store).

**Comment by anzipex** [comment]
Both versions [1.0.3](https://github.com/retronx-team/sys-clk/releases/tag/1.0.3) or [2.0.0-rc](https://github.com/retronx-team/sys-clk/releases/tag/2.0.0-rc) don't work with Switch firmware 17.0.0, but after downgrading to 16.1.0 both versions of sys-clk works fine

**Comment by p-sam** [comment]
Please check status with the latest sys-clk prerelease binaries (version should show 2.0.0-rc-4-xxxx), and upload new reports if issues still persist

**Comment by Octogonee** [comment]
Works after reinstalling 2.0.0-rc. Closing.
