### ISSUE TITLE
"Do not Override" option in 1.9.0 does not revert frequencies

### ISSUE THREAD

**Issue by ciucciodifuoco** [retronx-team/sys-clk#73]
Hi!

i just updated the OC suite on my Switch Lite and noticed that now the "Do not override" option when selecting CPU,GPU and RAM clocks does not revert the frequencies to the default state. 
Step to reproduce:

1 - Launch a game and have it on a profile that has only "Do not override" options, so all the clocks are stock one (i.e. 384mhz for GPU)
2 - Set one of the clocks to a different value (i.e. GPU clock to 768mhz)
3 - Let's say you want to revert the change and go back to stock clock, if you now change the frequency to "Do not override" the clock will not change back to default (i.e. GPU clock will be kept at 768mhz instead of going back to 384mhz)

This option was working fine in previous versions.

**Comment by p-sam** [comment]
Wrong repo
