### ISSUE TITLE
1996mhz memory missing (OLED)?

### ISSUE THREAD

**Issue by Kido1986** [retronx-team/sys-clk#78]
I just updated to 17.0.1 on a fresh SD card (old one died had to start over from scratch).  I previously could set RAM to 1996Mhz but now it's limited to 1600.  Is this by design or is there something not right (or did I make a mistake)?

On newest 2.0 RC

**Comment by Kido1986** [comment]
Reading through the code, it looks like this version only supports 1600mhz max, if my very rudimentary coding (lack of) skills are correct?  Is there any 1996mhz will be added back within the 2.0 releases?

**Comment by p-sam** [comment]
You're probably thinking of a fork/unofficial version, there's never been such option
