### ISSUE TITLE
Not working on 18.0.1: sys-clk does not seem to be running

### ISSUE THREAD

**Issue by AlexbossNFS** [retronx-team/sys-clk#81]

**Comment by impeeza** [comment]
The code needs to be updated to latest LibNX @retronx-team, can you please help us with the updated code?  thanks a lot.

**Comment by Jan64X** [comment]
Any updates on this?

**Comment by p-sam** [comment]
I can only assume it's another installation problem, with no description or logs

**Comment by NWPlayer123** [comment]
@p-sam the needing to be updated for libnx is a valid complaint, `svcQueryIoMapping` was "fixed" to `svcQueryMemoryMapping` a couple weeks after 2.0.0-rc so master currently doesn't compile without that change https://github.com/switchbrew/libnx/commit/933c5a12f0f23a330c91a8483dd022038cf00af2#diff-f67067f73a50b3bb9ae93952e1f9f9afc84c5ed2b0f723eba8123cc5f5caddc0L1121

**Comment by p-sam** [comment]
that I can fix, thx

**Comment by impeeza** [comment]
This is the error building with latest DevKitPro:

![image](https://github.com/retronx-team/sys-clk/assets/41979604/ef266ad0-1ee2-44b0-9c09-7e37afe3a2bc)

**Comment by impeeza** [comment]
I just apply the changes on this patch file

```
diff -Naur a/sysmodule/lib/nxExt/src/t210.c b/sysmodule/lib/nxExt/src/t210.c
--- a/sysmodule/lib/nxExt/src/t210.c
+++ b/sysmodule/lib/nxExt/src/t210.c
@@ -175,7 +175,7 @@
     if(hosversionAtLeast(10,0,0))
     {
         u64 out_size;
-        return svcQueryIoMapping(virtaddr, &out_size, physaddr, size);
+        return svcQueryMemoryMapping(virtaddr, &out_size, physaddr, size);
     }
     else
     {
diff -Naur a/sysmodule/perms.json b/sysmodule/perms.json
--- a/sysmodule/perms.json
+++ b/sysmodule/perms.json
@@ -111,7 +111,7 @@
 				"svcCreateEvent": "0x45",
 				"svcCreateInterruptEvent": "0x53",
 				"svcReadWriteRegister": "0x4E",
-				"svcQueryIoMapping": "0x55",
+				"svcQueryMemoryMapping": "0x55",
 				"svcCreateDeviceAddressSpace": "0x56",
 				"svcAttachDeviceAddressSpace": "0x57",
 				"svcDetachDeviceAddressSpace": "0x58",


```

And was able to build using latest DevKitPro, Libnx and LibTesla


![image](https://github.com/retronx-team/sys-clk/assets/41979604/76285eef-b6fa-49d0-8d66-9ece330354bb)
