### ISSUE TITLE
hbmenu crash’s once a game is open 18.1.0

### ISSUE THREAD

**Issue by 91ajames** [retronx-team/sys-clk#83]
I can access the hbmenu from photos ok,
Once I open a game, eq, the start screen or middle of a game, and I go back to hbmenu, it freezes once I click on photo’s into a white screen causes me to loose my game. Force power button for a reboot.

Other than that, works fine under Tesla-Menu. I just have to make sure I’m not under a game to access hbmenu.

NSV 18.1.0 1.7.1 S/E
Hbmenu 3.6.0
Nx-loader 2.4.4

**Comment by p-sam** [comment]
I assume you either fixed your issue, or stopped trying. I'll be closing this since it looks like a support problem rather than a sys-clk issue
