### ISSUE TITLE
R-Joycon BT connection interference

### ISSUE THREAD

**Issue by caller0** [retronx-team/sys-clk#84]
I've been having an issue for months now when playing on TV with my Switch Oled docked, always thought it might be my R-joycon that was faulty, but now I noticed the exact same issue with a 3rd party pair of joycons, always the right one disconnecting from time to time, even when very close to the docked Switch (like if your own hand is breaking the signal and disconnects the joycon sometimes).
After some Google research, I found that some more people have the exact same issue, always with the R-joycon... Some of them "solved" it disconnecting USB3.0 an Ethernet adapter from the dock (which is not my case, with the Oled Dock and always using wifi/airplane mode), but all seemed to confirm that DELETING Sys-clk from the SD solved (or at least reduced) the issue.

So, my question is, could you guys look into it, try to reproduce the issue and possibly find a way to fix it? I don't want to stop using Sys-clk, but having my R-Joycons losing connection all the time is annoying as hell...

**Comment by caller0** [comment]
Here are a couple of examples of people reporting the same issue on the Atmosphere-NX github issues page.
https://github.com/Atmosphere-NX/Atmosphere/issues/2229
https://github.com/Atmosphere-NX/Atmosphere/issues/2113#issuecomment-1776416656

**Comment by p-sam** [comment]
I'd suggest removing `usb30_force_enabled` from your system_settings.ini, that's the only thing I can think of (in software) that can interfere directly with connectivity. Also, you can try being closer to the switch, and griping that joycon differently since the antennas are placed at your fingers, not using bt audio, etc.

**Comment by caller0** [comment]
I see. I will try that, thank you very much for your time replying this issue, I appreciate it. And thanks for the awesome work with sys-clk also!
