### ISSUE TITLE
1963 / 998 MHZ Cpu/Gpu clock on Mariko

### ISSUE THREAD

**Issue by souldbminerr** [retronx-team/sys-clk#89]
Both of these clocks are considered safe on mariko (998 only in docked)
Nvidia's official maxes for X1+ are 1963 / 1267, both are safe with good speedo
1152 is safe on docked though even with bad speedo

**Comment by p-sam** [comment]
You seem to be mistaking this repo for something else.

sys-clk uses the frequency lists reported by your system directly from PCV
