### ISSUE TITLE
Constantly underclocking

### ISSUE THREAD

**Issue by fergatr0n** [retronx-team/sys-clk#9]
No matter what I try or how I configure, the CPU gets automatically under clocked to 510.  I tried 1581 and 1224 but both go to 501.  Any ideas?

**Comment by p-sam** [comment]
Yea there will be a hotfix release accomodating for that, the cap was incorrectly targeted at CPU on 0.12.0

**Comment by m4xw** [comment]
🙈

**Comment by p-sam** [comment]
An hotfix release 0.12.1 as been made, you can download it on the releases. Thanks for the report
