### ISSUE TITLE
Switch just stop working and freezes

### ISSUE THREAD

**Issue by Lines25** [retronx-team/sys-clk#90]
When I'm launching my games, when it's loading all my switch freezes and just won't working without reboot by pressing power btn 15secs and start it again

Specs: Mariko (rev. 2) chipped, kefir latest at this moment (756), sys-clk latest at this moment too (2.0.1).

I have tried fully reinstall kefir via update HB app and it didn't help !

**Comment by p-sam** [comment]
You probably have something installed that interferes with sys-clk, try only installing atmosphere and sys-clk via official releases
