### ISSUE TITLE
Why have a "cheat sheet" when you could just put it in the normal lists?

### ISSUE THREAD

**Issue by Scouter953** [retronx-team/sys-clk#91]
I find it incredibly odd that there's a cheat sheet section when it seems ridiculously easy to just list it like "921mhz - Maximum," "768mhz - Official Docked," etc. As it stands it's just incredibly clunky and the easiest solution becomes taking a picture of the cheat sheet with my phone.

**Comment by p-sam** [comment]
I'm not sure what's the problem here, but thanks for sharing

**Comment by souldbminerr** [comment]
Will PR this.
