### ISSUE TITLE
Add support for 1963 CPU / 998 GPU frequencies for Mariko units

### ISSUE THREAD

**Issue by souldbminerr** [retronx-team/sys-clk#92]
Hello!
I know that increasing the cap isnt something planned, but whatever.
The official Tegra X1+ max clocks are 1963/1267. People have managed to do 2601/1497. I know that is out of scope for this project. However, 1963/998 is safe for Mariko units when docked

**Comment by p-sam** [comment]
Hello

>  I know that is out of scope for this project

You already know

**Comment by souldbminerr** [comment]
I mean unlocking 1963/998 on mariko. It is 100% safe in docked
