### ISSUE TITLE
Decrease GPU cap in docked for Erista

### ISSUE THREAD

**Issue by souldbminerr** [retronx-team/sys-clk#93]
Erista 1785/921 is not reccomended without undervolt. It raises temps significantly. 1581/768 is what should be the cap if sys-clk aims to be safe

**Comment by p-sam** [comment]
I feel like even what's in place for handheld profiles would not be enough anyway. The safest bet would be to remove sys-clk altogether from your switch, or to only bump what's necessary on a game by game basis  (like designed)
